name: "tsql_utils_dbt_utils_integration_tests"
version: "1.0"
config-version: 2

profile: "integration_tests"

dispatch:
  - macro_namespace: dbt_utils
    search_order:
      [
        "tsql_utils_dbt_utils_integration_tests",
        "tsql_utils",
        "dbt",
        "dbt_utils_integration_tests",
        "dbt_utils",
      ]

models:
  dbt_utils_integration_tests:
    index: HEAP # Synapse only
    as_columnstore: "{{ target.type != 'sqlserver' }}"
    enabled: true
    web:
      # TODO: fix these!
      # see: https://github.com/dbt-msft/tsql-utils/issues/66
      test_url_host: &disabled
        enabled: false
      test_url_path: *disabled
      test_urls: *disabled
    cross_db_utils: *disabled
    sql:
      # BROKEN BC MACROS ARE UNPORTED STILL
      test_generate_series: *disabled
      test_get_column_values: *disabled
      test_get_relations_by_pattern: *disabled
      test_get_relations_by_prefix_and_union: *disabled
      # broken bc TSQL will never support
      test_groupby: *disabled
      test_union: *disabled
      test_unpivot_bool: *disabled
    materializations:
      # TODO: fix error
      # https://github.com/dbt-msft/tsql-utils/issues/67
      test_insert_by_period: *disabled
  # intractable nested CTEs from
  # https://github.com/calogica/dbt-date/pull/30
tests:
  dbt_utils_integration_tests: *disabled
seeds:
  dbt_utils_integration_tests:
    cross_db: *disabled
    schema_tests:
      data_test_sequential_timestamps:
        +column_types:
          my_timestamp: datetime2
      # can't override dbt_utils's test def args
      data_test_unique_where: *disabled
      data_test_not_null_where: *disabled
      # more like above: something weird happening: `Incorrect syntax near '<'.`
      data_test_mutually_exclusive_ranges_with_gaps_zero_length: *disabled
      data_test_mutually_exclusive_ranges_no_gaps: *disabled
      data_test_mutually_exclusive_ranges_with_gaps: *disabled

    sql:
      # not yet ported, or can't be??
      data_unpivot_bool: *disabled
      data_unpivot_bool_expected: *disabled
      # data_get_query_results_as_dict: *not-synapse
