fabric_d365:
  outputs:
    dev:
      authentication: ServicePrincipal
      tenant_id: 2ed3be0e-193e-4886-aceb-0c1032a74a31
      client_id: 8c8e543b-be77-4e9b-a634-d138dce5bd57
      client_secret: XQE8Q~7g2jtbSvO_wjcelqpc21vW.vQ9J2dDibFK
      database: dw_gold
      driver: ODBC Driver 18 for SQL Server
      host: b27nglr6dgderlhlbqidfj2kge-uf6n4xvquwoejm7ep7blowjgei.datawarehouse.fabric.microsoft.com
      schema: dbo
      threads: 4
      type: fabric
  target: dev