name: "tsql_utils_dbt_date_integration_tests"
version: "1.0"
config-version: 2

profile: "integration_tests"

dispatch:
  - macro_namespace: dbt_utils
    search_order:
      [
        "tsql_utils_dbt_date_integration_tests",
        "tsql_utils",
        "dbt",
        "dbt_utils",
      ]
  - macro_namespace: dbt_date
    search_order:
      ["tsql_utils_dbt_date_integration_tests", "tsql_utils", "dbt", "dbt_date"]

vars:
  "dbt_date:time_zone": "Pacific Standard Time"

models:
  dbt_date_integration_tests:
    schema: dbt_date_integration_tests
    materialized: table
    # needed bc of
    # https://github.com/calogica/dbt-date/pull/30
    # enabled: false (THIS SHOULD WORK BUT DOESN'T!?)
    # test_dates:
    #   enabled: true
    dates: &disabled
      enabled: false
    dim_week: *disabled
    dim_date: *disabled
    dim_date_fiscal: *disabled
    dim_hour: *disabled
